# Generated by Django 4.1.7 on 2023-03-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('idattendance', models.AutoField(primary_key=True, serialize=False)),
                ('iduser', models.IntegerField(unique=True)),
                ('date', models.CharField(max_length=10)),
                ('hours', models.CharField(max_length=6)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='USERADMIN',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mame', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('idt', models.CharField(max_length=20, unique=True)),
                ('hour', models.CharField(max_length=15)),
            ],
        ),
    ]
