# Generated by Django 4.1.7 on 2023-03-23 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('idt', models.CharField(max_length=20, unique=True)),
                ('hour', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('idattendance', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=10)),
                ('hours', models.CharField(max_length=6)),
                ('status', models.BooleanField()),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.users')),
            ],
        ),
    ]
